services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cpp.rule=Host(`cpp.alpi314.com`)"
      - "traefik.http.routers.cpp.tls=true"
      - "traefik.http.routers.cpp.tls.certresolver=traefik-letsencrypt"
      - "traefik.http.services.cpp.loadbalancer.server.port=80"

      # Security Headers
      - "traefik.http.routers.cpp.middlewares=secure-headers@docker"
      - "traefik.http.middlewares.secure-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.secure-headers.headers.permissionsPolicy=camera=(), microphone=(), geolocation=()"
      - "traefik.http.middlewares.secure-headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"
      - "traefik.http.middlewares.secure-headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
    network_mode: traefik
